# Generated by Django 6.1.1 on 2026-10-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('state', models.IntegerField(max_length=2)),
                ('rack_id', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'city'], name='stations_fu_state_64a61f_idx')],
            },
        ),
    ]
