# Generated by Django 6.1.1 on 2026-10-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
