# Generated by Django 6.1.1 on 2026-10-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_fuelstation_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=120)),
                ('key', models.CharField(max_length=120)),
                ('whole_key', models.CharField(max_length=120)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('is_statistical', models.BooleanField()),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'key'], name='stations_ce_state_d582cd_idx'), models.Index(fields=['state', 'whole_key'], name='stations_ce_state_58f2cf_idx')],
            },
        ),
    ]
