# Generated by Django 6.1.1 on 2026-10-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_censusplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusplace',
            name='land_area',
            field=models.FloatField(default=0),
        ),
    ]
